# Generated by Django 4.2.16 on 2024-09-10 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_myself_product_delete_moodentry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Myself',
        ),
        migrations.AddField(
            model_name='product',
            name='kelas',
            field=models.CharField(default='PBP', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='nama',
            field=models.CharField(default='mahasiswa', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='npm',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='a car'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='car', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default='0'),
        ),
    ]
