# Generated by Django 4.2.16 on 2024-09-16 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_person_alter_product_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.RemoveField(
            model_name='product',
            name='kelas',
        ),
        migrations.RemoveField(
            model_name='product',
            name='nama',
        ),
        migrations.RemoveField(
            model_name='product',
            name='npm',
        ),
    ]
